import vocabulary from "./vocabulary.json";

/**
 * Checks generated JSON-LD against the real schema.org vocabulary.
 *
 * The failure this exists to catch is markup that looks completely right and is
 * silently wrong — `availableLanguage` on a business rather than `knowsLanguage`,
 * a `Text` where a node is expected, a property that belongs on a parent type
 * the business does not inherit from. None of that throws, none of it shows up
 * in review, and a crawler simply ignores the property. The fact never reaches
 * an answer engine and nothing anywhere says so.
 *
 * The vocabulary is generated by scripts/build-vocabulary.ts from schema.org
 * itself, so this checks against what the standard actually says rather than
 * what anyone remembered.
 *
 * Deliberately not a full JSON-LD or SHACL validator. It answers three
 * questions — does the property exist, is it allowed on this type, is the value
 * roughly the right shape — which is where the real mistakes are.
 */

export interface SchemaIssue {
  /** Dotted path to the offending node, e.g. "@graph[0].geo". */
  path: string;
  severity: "error" | "warning";
  message: string;
}

const TYPES = vocabulary.types as Record<string, string[]>;
const VALUE_TYPES = vocabulary.valueTypes as Record<string, string[]>;
const ENUMERATIONS = new Set(vocabulary.enumerations as string[]);

/** Keys that are JSON-LD syntax rather than schema.org properties. */
const JSONLD_KEYS = new Set(["@context", "@graph", "@id", "@type", "@value", "@list", "@reverse"]);

/** schema.org types whose values are written as plain JSON scalars. */
const LITERAL_TYPES = new Set([
  "Text",
  "URL",
  "Number",
  "Integer",
  "Float",
  "Boolean",
  "Date",
  "DateTime",
  "Time",
  "Duration",
  "CssSelectorType",
  "XPathType",
  "PronounceableText",
]);

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Whether a value's shape is compatible with the property's declared range.
 *
 * Intentionally forgiving. schema.org allows a URL almost anywhere a node is
 * allowed (as a reference), enumerations are written as URL strings, and many
 * ranges include both Text and a node type. Only a clear contradiction is
 * reported — an object where nothing but Text is allowed, or a bare string
 * where only a structured node makes sense.
 */
function checkValueShape(property: string, value: unknown): string | null {
  const ranges = VALUE_TYPES[property];
  if (!ranges || ranges.length === 0) return null;

  const allowsLiteral = ranges.some((range) => LITERAL_TYPES.has(range));
  const allowsNode = ranges.some((range) => !LITERAL_TYPES.has(range));
  // An enumeration member is written as its URL, so a string satisfies the
  // range even though the range names a class.
  const allowsEnum = ranges.some((range) => ENUMERATIONS.has(range));

  if (isPlainObject(value)) {
    // A node where only text is allowed.
    if (!allowsNode) {
      return `expects ${ranges.join(" or ")}, got an object`;
    }
    return null;
  }

  if (typeof value === "string") {
    // A string where a node is required is usually fine — schema.org reads it
    // as a URL reference — but not when the range has no URL and no Text.
    if (!allowsLiteral && !allowsEnum && !ranges.includes("URL")) {
      return `expects ${ranges.join(" or ")}, got a string`;
    }
    return null;
  }

  if (typeof value === "number" || typeof value === "boolean") {
    if (!allowsLiteral) return `expects ${ranges.join(" or ")}, got a ${typeof value}`;
    return null;
  }

  return null;
}

function validateNode(node: Record<string, unknown>, path: string, issues: SchemaIssue[]): void {
  const rawType = node["@type"];
  const types = (Array.isArray(rawType) ? rawType : [rawType])
    .filter((entry): entry is string => typeof entry === "string");

  if (types.length === 0) {
    // `{"@id": "..."}` is a reference to a node defined elsewhere in the graph,
    // not an untyped node. It is the correct way to point one node at another
    // and carries no properties of its own to check.
    const keys = Object.keys(node);
    if (keys.length === 1 && keys[0] === "@id") return;

    issues.push({
      path,
      severity: "warning",
      message: "node has no @type, so nothing can be validated against it",
    });
    return;
  }

  // Union of every listed type's properties. A node typed as two things may
  // legitimately carry properties of either.
  const allowed = new Set<string>();
  const unknownTypes: string[] = [];

  for (const type of types) {
    const properties = TYPES[type];
    if (!properties) {
      unknownTypes.push(type);
      continue;
    }
    for (const property of properties) allowed.add(property);
  }

  if (unknownTypes.length === types.length) {
    issues.push({
      path,
      severity: "warning",
      message:
        `@type ${unknownTypes.join(", ")} is not in the bundled vocabulary, so its ` +
        `properties were not checked. Add it to scripts/build-vocabulary.ts and re-run.`,
    });
    return;
  }

  for (const [key, value] of Object.entries(node)) {
    if (JSONLD_KEYS.has(key)) continue;

    if (!allowed.has(key)) {
      // Distinguish "no such property anywhere" from "not valid on this type".
      // They have different fixes, and conflating them sends people hunting for
      // a typo that isn't there.
      const existsElsewhere = VALUE_TYPES[key] !== undefined;
      issues.push({
        path: `${path}.${key}`,
        severity: "error",
        message: existsElsewhere
          ? `"${key}" is a real schema.org property but is not valid on ${types.join("/")} — ` +
            `crawlers will ignore it`
          : `"${key}" is not a schema.org property — check the spelling`,
      });
      continue;
    }

    const values = Array.isArray(value) ? value : [value];
    for (const [index, entry] of values.entries()) {
      const entryPath = Array.isArray(value) ? `${path}.${key}[${index}]` : `${path}.${key}`;

      const problem = checkValueShape(key, entry);
      if (problem) {
        issues.push({ path: entryPath, severity: "warning", message: `"${key}" ${problem}` });
      }

      if (isPlainObject(entry)) validateNode(entry, entryPath, issues);
    }
  }
}

/**
 * Validates a full JSON-LD graph.
 *
 * Errors mean a crawler will drop the property. Warnings mean it is probably
 * fine but worth a look.
 */
export function validateJsonLd(graph: Record<string, unknown>): SchemaIssue[] {
  const issues: SchemaIssue[] = [];
  const nodes = graph["@graph"];

  if (!Array.isArray(nodes)) {
    // A single node rather than a graph is still valid JSON-LD.
    if (isPlainObject(graph)) validateNode(graph, "root", issues);
    return issues;
  }

  for (const [index, node] of nodes.entries()) {
    if (isPlainObject(node)) validateNode(node, `@graph[${index}]`, issues);
  }

  return issues;
}

/** One line per issue, for console output and the portal's output panel. */
export function formatIssues(issues: SchemaIssue[]): string[] {
  return issues.map(
    (issue) => `${issue.severity === "error" ? "ERROR" : "warn "}  ${issue.path}  ${issue.message}`
  );
}
