import * as fs from "fs";
import * as path from "path";

/**
 * Distils schema.org's vocabulary into the subset this app can emit.
 *
 *   npx tsx scripts/build-vocabulary.ts
 *
 * The full vocabulary is ~1.5MB of JSON-LD describing 3,200 terms. Shipping all
 * of it to validate a dozen node types would be absurd, and hand-writing the
 * property list from memory would reproduce exactly the mistake the validator
 * exists to catch — `availableLanguage` on a business looks right and is wrong.
 *
 * So: fetch the real vocabulary, walk the class hierarchy for the types we
 * actually emit, and write out only their properties. Re-run when schema.org
 * changes or when the builder starts emitting a new type.
 */

const SOURCE = "https://schema.org/version/latest/schemaorg-current-https.jsonld";
const OUT = path.join(__dirname, "..", "src", "jsonld", "vocabulary.json");

/**
 * Types the builder emits. Anything the graph contains must be listed here or
 * the validator has nothing to check it against.
 */
const ROOT_TYPES = [
  // Business types. LocalBusiness subtypes are configurable per tenant, so the
  // common trades are all included rather than only the ones seen so far.
  "LocalBusiness",
  "Plumber",
  "HVACBusiness",
  "Electrician",
  "RoofingContractor",
  "GeneralContractor",
  "HomeAndConstructionBusiness",
  "MovingCompany",
  "Locksmith",
  "HousePainter",
  "Organization",
  // Supporting nodes.
  "PostalAddress",
  "GeoCoordinates",
  "OpeningHoursSpecification",
  "QuantitativeValue",
  "ContactPoint",
  "PropertyValue",
  "Person",
  "City",
  "OfferCatalog",
  "Offer",
  "Service",
  "EducationalOccupationalCredential",
  "FAQPage",
  "Question",
  "Answer",
  "WebSite",
  "ReserveAction",
  "EntryPoint",
  "Reservation",
];

interface Term {
  "@id": string;
  "@type"?: string | string[];
  "rdfs:subClassOf"?: { "@id": string } | { "@id": string }[];
  "schema:domainIncludes"?: { "@id": string } | { "@id": string }[];
  "schema:rangeIncludes"?: { "@id": string } | { "@id": string }[];
}

const asArray = <T,>(value: T | T[] | undefined): T[] =>
  value === undefined ? [] : Array.isArray(value) ? value : [value];

const bare = (id: string): string => id.replace(/^schema:/, "");

async function main(): Promise<void> {
  process.stdout.write(`Fetching ${SOURCE}\n`);
  const response = await fetch(SOURCE);
  if (!response.ok) throw new Error(`HTTP ${response.status} fetching the vocabulary`);

  const doc = (await response.json()) as { "@graph": Term[] };
  const graph = doc["@graph"] ?? [];
  process.stdout.write(`  ${graph.length} terms\n\n`);

  const byId = new Map<string, Term>();
  for (const term of graph) byId.set(term["@id"], term);

  /** Every ancestor of a type, including itself. */
  const ancestors = (name: string): string[] => {
    const out: string[] = [];
    const walk = (id: string): void => {
      if (out.includes(bare(id))) return;
      out.push(bare(id));
      const term = byId.get(id);
      for (const parent of asArray(term?.["rdfs:subClassOf"])) walk(parent["@id"]);
    };
    walk(`schema:${name}`);
    return out;
  };

  // A property is valid on a type if its domain includes that type or any
  // ancestor — `name` is declared on Thing and inherited by everything.
  const properties: Record<string, string[]> = {};
  const valueTypes: Record<string, string[]> = {};

  for (const type of ROOT_TYPES) {
    const family = new Set(ancestors(type));
    if (family.size === 1 && !byId.has(`schema:${type}`)) {
      process.stdout.write(`  ! ${type} is not in the vocabulary — check the spelling\n`);
      continue;
    }

    const allowed: string[] = [];
    for (const term of graph) {
      if (term["@type"] !== "rdf:Property") continue;
      const domains = asArray(term["schema:domainIncludes"]).map((d) => bare(d["@id"]));
      if (!domains.some((domain) => family.has(domain))) continue;

      const property = bare(term["@id"]);
      allowed.push(property);
      if (!valueTypes[property]) {
        valueTypes[property] = asArray(term["schema:rangeIncludes"]).map((r) => bare(r["@id"]));
      }
    }

    properties[type] = allowed.sort();
  }

  // Enumeration members are written as URLs — "https://schema.org/Monday" — so
  // a string is the correct value for any property whose range is an
  // enumeration. Without knowing which types those are, the validator flags
  // every dayOfWeek in the graph.
  const enumerations: string[] = [];
  for (const term of graph) {
    if (term["@type"] !== "rdfs:Class") continue;
    if (ancestors(bare(term["@id"])).includes("Enumeration")) {
      enumerations.push(bare(term["@id"]));
    }
  }

  const out = {
    enumerations: enumerations.sort(),
    _comment:
      "Generated by scripts/build-vocabulary.ts from schema.org. Do not edit by hand — " +
      "re-run the script instead.",
    _source: SOURCE,
    types: properties,
    valueTypes,
  };

  fs.writeFileSync(OUT, JSON.stringify(out, null, 1) + "\n", "utf8");

  const size = (fs.statSync(OUT).size / 1024).toFixed(0);
  process.stdout.write(`Wrote ${OUT}\n`);
  process.stdout.write(`  ${Object.keys(properties).length} types, `);
  process.stdout.write(`${Object.keys(valueTypes).length} properties, ${size}KB\n`);
  for (const type of ROOT_TYPES.slice(0, 3)) {
    process.stdout.write(`  ${type.padEnd(24)} ${properties[type]?.length ?? 0} properties\n`);
  }
}

main().catch((error) => {
  process.stderr.write(`\nFailed: ${error instanceof Error ? error.message : error}\n`);
  process.exit(1);
});
